import pandas as pd
import datetime

class ReportGenerator:
    """
    Generates an HTML report summarizing the entire AutoML process:
    - Dataset Statistics
    - Issues Detected & User Decisions
    - Preprocessing Configuration
    - Model Comparison Table
    - Best Model Metrics
    """
    def __init__(self, dataset, target_column, issues, user_decisions, preprocessing_config, model_results, best_model):
        self.dataset = dataset
        self.target_column = target_column
        self.issues = issues
        self.user_decisions = user_decisions
        self.preprocessing_config = preprocessing_config
        self.model_results = model_results
        self.best_model = best_model

    def generate_html_report(self):
        # Current timestamp
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Basic HTML Template using f-strings
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>AutoML Project Report</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background-color: #f9f9f9; color: #333; }}
                .container {{ background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                h2 {{ color: #2980b9; margin-top: 30px; }}
                .metric-box {{ background: #ecf0f1; padding: 15px; border-radius: 5px; margin: 10px 0; }}
                table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
                th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
                th {{ background-color: #3498db; color: white; }}
                tr:nth-child(even) {{ background-color: #f2f2f2; }}
                .highlight {{ font-weight: bold; color: #27ae60; }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🤖 AutoML Execution Report</h1>
                <p><strong>Generated on:</strong> {timestamp}</p>

                <h2>1. Dataset Overview</h2>
                <div class="metric-box">
                    <p><strong>Target Column:</strong> {self.target_column}</p>
                    <p><strong>Total Rows:</strong> {len(self.dataset)}</p>
                    <p><strong>Total Columns:</strong> {len(self.dataset.columns)}</p>
                </div>

                <h2>2. Data Quality Issues & User Decisions</h2>
                {self._generate_issues_table()}

                <h2>3. Preprocessing Configuration</h2>
                <ul>
                    <li><strong>Missing Value Strategy:</strong> {self.preprocessing_config.get('missing_strategy', 'N/A')}</li>
                    <li><strong>Outlier Strategy:</strong> {self.preprocessing_config.get('outlier_strategy', 'N/A')}</li>
                    <li><strong>Scaling Strategy:</strong> {self.preprocessing_config.get('scaling_strategy', 'N/A')}</li>
                    <li><strong>Encoding Strategy:</strong> {self.preprocessing_config.get('encoding_strategy', 'N/A')}</li>
                    <li><strong>Test Split Size:</strong> {float(self.preprocessing_config.get('test_size', 0.2))*100}%</li>
                </ul>

                <h2>4. Model Performance Comparison</h2>
                {self._generate_model_table()}

                <h2>5. 🏆 Best Model Selected</h2>
                <div class="metric-box" style="border-left: 5px solid #27ae60;">
                    <h3>{self.best_model['Model']}</h3>
                    <p><strong>F1-Score:</strong> <span class="highlight">{self.best_model.get('F1-Score', 0):.4f}</span></p>
                    <p><strong>Accuracy:</strong> {self.best_model.get('Accuracy', 0):.4f}</p>
                    <p><strong>Precision:</strong> {self.best_model.get('Precision', 0):.4f}</p>
                    <p><strong>Recall:</strong> {self.best_model.get('Recall', 0):.4f}</p>
                </div>

                <hr>
                <p style="text-align: center; font-size: 0.9em; color: #7f8c8d;">Generated by Custom AutoML Pipeline</p>
            </div>
        </body>
        </html>
        """
        return html_content

    def _generate_issues_table(self):
        """Helper to create HTML table for issues"""
        if not self.issues:
            return "<p>✅ No data quality issues were detected.</p>"
        
        rows = ""
        for i, issue in enumerate(self.issues):
            decision_key = f"{issue['type']}_{i}"
            decision = self.user_decisions.get(decision_key, "Default/No Action")
            
            rows += f"""
            <tr>
                <td>{issue['type']}</td>
                <td>{issue.get('column', 'Global')}</td>
                <td>{issue.get('severity', 'Medium')}</td>
                <td>{decision}</td>
            </tr>
            """
            
        return f"""
        <table>
            <thead>
                <tr>
                    <th>Issue Type</th>
                    <th>Column</th>
                    <th>Severity</th>
                    <th>User Decision</th>
                </tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>
        """

    def _generate_model_table(self):
        """Helper to create HTML table for model results"""
        if not self.model_results:
            return "<p>⚠️ No model results available.</p>"
        
        # Convert dict to DataFrame for easier handling
        rows_list = []
        for model_name, metrics in self.model_results.items():
            row = metrics.copy()
            row['Model'] = model_name
            rows_list.append(row)
            
        df = pd.DataFrame(rows_list)
        
        # Reorder columns to ensure Model is first
        cols = ['Model'] + [c for c in df.columns if c != 'Model']
        df = df[cols]
        
        # Sort by F1 Score if available
        if 'F1-Score' in df.columns:
            df = df.sort_values('F1-Score', ascending=False)
            
        return df.to_html(classes='table', index=False, float_format="%.4f")